void comandi_client();
int check_dates(char*,char*,char);
void insert_entry(char,int);
int count_entries(char);
int sum_entries(char);
void write_aggr(int,int,char);
int check_aggr(int,char);
void wait_for_entries(int,int,char);
void send_missing_entries(int,char);